version: '3.1'

services:

  db:
    image: mariadb:10.6
    restart: always
    env_file:
      - .env
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - db
    ports:
      - "4301:8080"

  web:
    build: ./
    restart: always
    depends_on:
      - db
    ports:
      - "4302:8080"
